spring:
  application:
  name: games-api
  datasource:
    url: jdbc:postgresql://localhost:5432/games
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
